language: c
compiler:
    - gcc
    - clang
install: 
    - sudo apt-get update -qq
    - sudo apt-get -t testing install -q doxygen
script: 
    - cmake ./
    - make all
    - ctest --output-on-failure
